version: "2"
run:
  allow-parallel-runners: true
  allow-serial-runners: true
  timeout: 5m
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - "!$test"
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
    gocyclo:
      min-complexity: 10
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/brpaz/freshrss-cleaner)
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    goimports:
      local-prefixes:
        - github.com/brpaz/freshrss-cleaner
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
